In [1]:
pip install torch transformers scikit-learn matplotlib seaborn pandas tqdm

Requirement already satisfied: torch in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (2.9.1)
Requirement already satisfied: transformers in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (4.57.3)
Requirement already satisfied: scikit-learn in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (1.8.0)
Requirement already satisfied: matplotlib in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: seaborn in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: pandas in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: tqdm in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (4.67.1)
Requirement already satisfied: filelock in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from torch) (3.20.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from torch) (2025.12.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from transformers) (2.4.0)
Requirement already satisfied: packaging>=20.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from transformers) (0.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: scipy>=1.10.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from requests->transformers) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages (from requests->transformers) (2025.11.12)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import torch
from transformers import pipeline, AutoTokenizer, AutoModel
import json
import numpy as np
from sklearn.cluster import KMeans
from collections import defaultdict
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score
from tqdm import tqdm
import os
from sklearn.metrics.pairwise import cosine_similarity
from collections import defaultdict
import warnings
from itertools import permutations

/Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/LSD-Analysis/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
warnings.filterwarnings('ignore', category=RuntimeWarning)

In [4]:
# Load Pre-computed SinLlama Contextual Embeddings
print("Loading embeddings...")
century_embeddings = torch.load("../Data/XLM-R_All_Century_Embeddings.pt", weights_only=False)

# Filter Centuries (Keep only robust ones)
valid_centuries = ['13', '14', '15', '18', '19', '20']
century_embeddings = {k: v for k, v in century_embeddings.items() if k in valid_centuries}
print(f"Loaded centuries: {list(century_embeddings.keys())}")

Loading embeddings...
Loaded centuries: ['13', '14', '15', '18', '19', '20']

In [5]:
# Load Lemma Data for Aggregation
print("Loading lemma and token data...")
with open('../Data/century_lemmas.json', 'r', encoding='utf-8') as f:
    century_lemmas = json.load(f)

with open('../Data/century_tokens.json', 'r', encoding='utf-8') as f:
    century_tokens = json.load(f)

# Build Sentence-Aligned Lemma Map
# Structure: lemma_map[century][sentence_index][word_index] = lemma
lemma_lookup = defaultdict(lambda: defaultdict(dict))

for century in valid_centuries:
    if century not in century_lemmas: continue
    l_sentences = century_lemmas[century]
    
    for s_idx, l_sent in enumerate(l_sentences):
        for w_idx, lemma in enumerate(l_sent):
            if lemma:
                lemma_lookup[century][s_idx][w_idx] = lemma
print("Lemma lookup built.")

Loading lemma and token data...
Lemma lookup built.

In [6]:
lemma_lookup

defaultdict(<function __main__.<lambda>()>,
            {'13': defaultdict(dict,
                         {0: {0: 'අප',
                           1: 'බුදුන්',
                           2: 'සාරාස',
                           3: 'කප්සුවහස',
                           4: 'මතු',
                           5: 'කුලුණුනු',
                           6: 'වණ',
                           7: 'යුත්',
                           8: 'මහත',
                           9: 'ව',
                           10: 'සක්',
                           11: 'වැ',
                           12: 'දිවකුරු',
                           13: 'බුදුන්',
                           14: 'හමුව',
                           15: 'අත',
                           16: 'ප',
                           17: 'නිවන්',
                           18: 'සසර',
                           19: 'සේ',
                           20: 'පි',
                           21: 'සත',
                           22: 'සඳහා',
                           23: 'විඳි',
                           24: 'සසර',
                           25: 'දුක',
                           26: 'නිවන්',
                           27: 'සේ',
                           28: 'ගන්',
                           29: 'භව',
                           30: 'දුර්ග',
                           31: 'වද',
                           32: 'පැරුම',
                           33: 'පුර',
                           34: 'ත',
                           35: 'පුර',
                           36: 'පමුණ',
                           37: 'දසදහස',
                           38: 'ලෝදාහි',
                           39: 'දෙව්බඹ',
                           40: 'අයජ',
                           41: 'මෙන්',
                           42: 'කිඹුල්වත්හි',
                           43: 'උපද',
                           44: 'වැඩිව',
                           45: 'පමුණ',
                           46: 'මහභිනික්මන්',
                           47: 'කොට',
                           48: 'පැවිජි',
                           49: 'වැ',
                           50: 'මහ',
                           51: 'වීර්ය',
                           52: 'කොට',
                           53: 'බොධිපර්යංකාරූඪ',
                           54: 'වැ',
                           55: 'මාරවිජ',
                           56: 'කොට',
                           57: 'සර්වඥපදප්රාප්ත',
                           58: 'වැ',
                           59: 'හුනස්නෙන්',
                           60: 'නඟ',
                           61: 'පූර්වොත්තර',
                           62: 'දිශා',
                           63: 'භාග',
                           64: 'වැඩ',
                           65: 'සිටි',
                           66: 'සප්තාහ',
                           67: 'අනිමිසලෝචන',
                           68: 'යුගල',
                           69: 'පුද',
                           70: 'ලද',
                           71: 'ජය',
                           72: 'මහ',
                           73: 'බොධි',
                           74: 'තත',
                           75: 'ප්රභ',
                           76: 'ව',
                           77: 'ඵල',
                           78: 'රුහ',
                           79: 'මහ',
                           80: 'බොධි',
                           81: 'තදවය',
                           82: 'ව',
                           83: 'ශාඛා',
                           84: 'හා',
                           85: 'බොධි',
                           86: 'ය',
                           87: 'තුන',
                           88: 'මහ',
                           89: 'බොධී',
                           90: 'වංශ',
                           91: 'සහස්රරශ්ම',
                           92: 'විභක්ත',
                           93: 'පද',
                           94: 'අතුර',
                           95: 'පරිකථානුකූල',
                           96: 'පද',
                           97: 'ගන්',
                           98: 'වර්ණනා',
                           99: 'කර',
                           100: 'ලබ'},
                          1: {0: 'යස්ස',
                           1: 'ය',
                           2: 'චතුර්විධ',
                           3: 'පද',
                           4: 'කර',
                           5: 'නාමපද'},
                          2: {0: 'එ',
                           1: 'චතුර්විධ',
                           2: 'පද',
                           3: 'නම',
                           4: 'කවර',
                           5: 'නාම',
                           6: 'පද',
                           7: 'ආඛ්යාත',
                           8: 'පද',
                           9: 'උපසර්ග',
                           10: 'පද',
                           11: 'නිපාතපදයි'},
                          3: {0: 'එ',
                           1: 'නාම',
                           2: 'පද',
                           3: 'නම',
                           4: 'සර්වාර්ථයන්',
                           5: 'නමන්නෙන්',
                           6: 'නාම',
                           7: 'පද',
                           8: 'නම',
                           9: 'වේ',
                           10: 'එයින්',
                           11: 'කීහ'},
                          4: {0: 'ක්රියාවාචක',
                           1: 'පද',
                           2: 'ආඛ්යාත',
                           3: 'නම',
                           4: 'වේ',
                           5: 'එයින්',
                           6: 'කීහ'},
                          5: {0: 'ක්රියා',
                           1: 'ද්යෝතක',
                           2: 'පද',
                           3: 'උපසර්ග',
                           4: 'නම',
                           5: 'වේ',
                           6: 'එයින්',
                           7: 'කීහ'},
                          6: {0: 'දක්වන',
                           1: 'ලද',
                           2: 'පද',
                           3: 'ආද්යන්ත',
                           4: 'මධ්ය',
                           5: 'නිපතිත',
                           6: 'ව',
                           7: 'විචිත්රාර්ථ',
                           8: 'පද',
                           9: 'නිපාත',
                           10: 'නම',
                           11: 'වෙත්',
                           12: 'එයින්',
                           13: 'කීහ'},
                          7: {0: 'මේ',
                           1: 'චතුර්විධ',
                           2: 'පද',
                           3: 'ප්රයෝග',
                           4: 'දක්වන්නට',
                           5: 'කීහ'},
                          8: {0: 'ය',
                           1: 'තන්හි',
                           2: 'එ',
                           3: 'ය',
                           4: 'නිපාත',
                           5: 'අයොග',
                           6: 'ව්යවඡදකය',
                           7: 'අන්ය',
                           8: 'යොග',
                           9: 'ව්යවච්ඡේදකය',
                           10: 'අත්යන්තා',
                           11: 'යොග',
                           12: 'ව්ය',
                           13: 'ච්ඡේදකය',
                           14: 'යි',
                           15: 'ත්රිවිධ',
                           16: 'වූ',
                           17: 'අන්ය',
                           18: 'යොග',
                           19: 'ව්යවච්ඡේදක',
                           20: 'වේ'},
                          9: {0: 'එ',
                           1: 'විශෙෂණ',
                           2: 'කෙරෙන්',
                           3: 'පර',
                           4: 'කොට',
                           5: 'ප්රයෝග',
                           6: 'කර',
                           7: 'ලද',
                           8: 'එවකාරය',
                           9: 'අයොග',
                           10: 'ව්යවච්ඡේදක',
                           11: 'ව',
                           12: 'ය',
                           13: 'තන්හි',
                           14: 'සෙයින්',
                           15: 'විශෙෂ',
                           16: 'කෙරෙන්',
                           17: 'පර',
                           18: 'කොට',
                           19: 'ප්රයෝග',
                           20: 'කර',
                           21: 'ලද',
                           22: 'එ',
                           23: 'කාර',
                           24: 'ව'},
                          10: {0: 'ය',
                           1: 'තන්හි',
                           2: 'සෙයින්ක්රියායෙන්',
                           3: 'පර',
                           4: 'කොට',
                           5: 'ප්රයොග',
                           6: 'කර',
                           7: 'ලද',
                           8: 'එ',
                           9: 'කාර',
                           10: 'අත්යන්තා',
                           11: 'යොග',
                           12: 'ව්යවච්ඡේදක',
                           13: 'ව'},
                          11: {0: 'ය',
                           1: 'තන්හි',
                           2: 'සෙයින්වාක්යයන්',
                           3: 'ව්යවච්ඡේද',
                           4: 'ඵල',
                           5: 'වන',
                           6: 'බැවින්',
                           7: 'නිපාතයා',
                           8: 'ප්රයෝග',
                           9: 'නොකළද',
                           10: 'විවක්ෂා',
                           11: 'වශ',
                           12: 'ඔහු',
                           13: 'අර්ථ',
                           14: 'ප්රතීත',
                           15: 'වේ',
                           16: 'මැයි'},
                          12: {0: 'එයින්',
                           1: 'කීහ',
                           2: 'ධර්ම',
                           3: 'කීර්තිපාද'},
                          13: {0: 'අහීස', 1: 'මාධි', 2: 'කථා'},
                          14: {0: 'යනු',
                           1: 'දක්වන',
                           2: 'ලද',
                           3: 'බුදුහ',
                           4: 'අනන්තා',
                           5: 'පරිමාණ',
                           6: 'ගුණ',
                           7: 'ඇති'},
                          15: {0: 'කිසේය', 1: 'යත්'},
                          16: {0: 'බුදුහ',
                           1: 'රූප',
                           2: 'විලාසයෙනුදු',
                           3: 'වචන',
                           4: 'විලාසයෙනුදු',
                           5: 'ඥාන',
                           6: 'විලාසයෙනුදු',
                           7: 'අචින්ත්යයහ',
                           8: 'අවාච්යයහ',
                           9: 'අතුල්යහ',
                           10: 'අවෙද්යයෝයි'},
                          17: {0: 'එව්හ',
                           1: 'අචින්ත්ය',
                           2: 'වන',
                           3: 'බැවින්',
                           4: 'චින්තා',
                           5: 'විෂයාතික්රාන්තයහ',
                           6: 'අවාච්ය',
                           7: 'වන',
                           8: 'බැවින්',
                           9: 'වාග්',
                           10: 'විෂයාතික්රාන්ත',
                           11: 'සහ',
                           12: 'අතුල්',
                           13: 'වන',
                           14: 'බැවින්',
                           15: 'උපමා',
                           16: 'විෂයාතික්රාන්තයහ',
                           17: 'අද',
                           18: 'වන',
                           19: 'බැවින්',
                           20: 'ඥාන',
                           21: 'විෂයාතික්රාන්තයහ'},
                          18: {0: 'කපකුද',
                           1: 'ව',
                           2: 'දවස',
                           3: 'තම',
                           4: 'සේම',
                           5: 'ව',
                           6: 'බුදු',
                           7: 'කෙනෙකුනුදු',
                           8: 'කියත',
                           9: 'ගෙව',
                           10: 'ගුණ',
                           11: 'ඇති',
                           12: 'මහ',
                           13: 'මුහුද',
                           14: 'හෙළ',
                           15: 'සිදුහතුළුද',
                           16: 'කළ',
                           17: 'සැළද',
                           18: 'තම',
                           19: 'තම',
                           20: 'පමණ',
                           21: 'දියගන්නා',
                           22: 'සේ',
                           23: 'ඒ',
                           24: 'බුදු',
                           25: 'රජහු',
                           26: 'ගුණ',
                           27: 'මුහුද',
                           28: 'වන්',
                           29: 'පස',
                           30: 'බුදුහුද',
                           31: 'බුදු',
                           32: 'සවෝද',
                           33: 'තම',
                           34: 'තම',
                           35: 'නුවණ',
                           36: 'පමණ',
                           37: 'ගන්ති',
                           38: 'ගුණ',
                           39: 'පමණ',
                           40: 'ගන්',
                           41: 'නොනිසෝ'},
                          19: {0: 'ඥානගර්ජනා',
                           1: 'කර',
                           2: 'සමර්ථ',
                           3: 'ව',
                           4: 'ධර්ම',
                           5: 'සෙනෙවි',
                           6: 'සැරිය',
                           7: 'මහත',
                           8: 'ර',
                           9: 'වැනි',
                           10: 'මහ',
                           11: 'පුරුෂයන',
                           12: 'අවිෂ',
                           13: 'ව',
                           14: 'බුදු',
                           15: 'ගුණ',
                           16: 'පුහුද',
                           17: 'වැ',
                           18: 'කියම්',
                           19: 'හ',
                           20: 'සිත',
                           21: 'මදුරු',
                           22: 'දළ',
                           23: 'විදුර',
                           24: 'ගිරි',
                           25: 'විදුනාක්',
                           26: 'පින',
                           27: 'හැඹිළි',
                           28: 'දළ',
                           29: 'මහ',
                           30: 'පොළො',
                           31: 'උකුල',
                           32: 'දෙනු',
                           33: 'වැනි',
                           34: 'බැවින්',
                           35: 'තම',
                           36: 'හට',
                           37: 'අවිෂ',
                           38: 'වතුද',
                           39: 'ප්රසාද',
                           40: 'පරවශ',
                           41: 'වැ',
                           42: 'ප්රවචන',
                           43: 'වහල',
                           44: 'කොට',
                           45: 'ශ්රද්ධ',
                           46: 'බුද්ධි',
                           47: 'සම්පන්නජනයන්',
                           48: 'සඳහා',
                           49: 'කතිප',
                           50: 'ගුණ',
                           51: 'දක්වනු',
                           52: 'ලබ'},
                          20: {0: 'බුදුන්',
                           1: 'ගුණ',
                           2: 'පුහුදුනන්',
                           3: 'හාද',
                           4: 'සව්පස',
                           5: 'බුදුන්',
                           6: 'හාද',
                           7: 'සාධ',
                           8: 'රණ',
                           9: 'ගුණ',
                           10: 'ඇත්මය',
                           11: 'අසාධාරණ',
                           12: 'ගුණ',
                           13: 'ඇත්මැයි'},
                          21: {0: 'එ',
                           1: 'සෙසු',
                           2: 'තිරිසන',
                           3: 'හා',
                           4: 'සාධාරණ',
                           5: 'තණ',
                           6: 'කබල',
                           7: 'ගඳැත්කුස',
                           8: 'දිර',
                           9: 'සිව්',
                           10: 'දෑ',
                           11: 'ගඳ',
                           12: 'වන',
                           13: 'සෙයින්',
                           14: 'පුහුද',
                           15: 'ආදී',
                           16: 'හා',
                           17: 'සාධාරණ',
                           18: 'ව',
                           19: 'රූපශොභාද',
                           20: 'ධ්යානාභි',
                           21: 'ඥාදි',
                           22: 'ගුණයෝද',
                           23: 'බුදු',
                           24: 'සතන්හිලා',
                           25: 'අසාධාරණ',
                           26: 'ව',
                           27: 'නොරබීජ',
                           28: 'න',
                           29: 'සිටි',
                           30: 'සිංහ',
                           31: 'තෙල',
                           32: 'සෙයින්',
                           33: 'දශබල',
                           34: 'චතුර්වෛශාරද්යාදි',
                           35: 'අසාධාරණ',
                           36: 'ගුණ',
                           37: 'ව',
                           38: 'කල',
                           39: 'නොබුද',
                           40: 'සතන්හි',
                           41: 'ල',
                           42: 'නොසිටි'},
                          22: {0: 'ඔවු',
                           1: 'රූප',
                           2: 'විලාස',
                           3: 'නම',
                           4: 'කවර'},
                          23: {0: 'ද්වාත්රිංශන්මහා',
                           1: 'පුරුෂ',
                           2: 'ලක්ෂණ',
                           3: 'හා',
                           4: 'අශීති',
                           5: 'අනුව්යංජන',
                           6: 'ප්රජ්වලිත',
                           7: 'රූප',
                           8: 'ශොභ'},
                          24: {0: 'එ',
                           1: 'ද්වාත්රිංගන්',
                           2: 'මහ',
                           3: 'පුරුෂ',
                           4: 'ලක්ෂණ',
                           5: 'නම',
                           6: 'කවර'},
                          25: {0: 'වදාළ', 1: 'මැන', 2: 'බුදුන්', 3: 'විසින්'},
                          26: {0: 'මෙහි',
                           1: 'ය',
                           2: 'තන්හි',
                           3: 'සුප්රතිෂ්ඨිතපාදත',
                           4: 'නම',
                           5: 'කවර'},
                          27: {0: 'අන',
                           1: 'පතුල',
                           2: 'බිම',
                           3: 'ඔබ',
                           4: 'කල',
                           5: 'අග්ර',
                           6: 'පාද',
                           7: 'තල',
                           8: 'හෝ',
                           9: 'පාර්ෂණි',
                           10: 'හෝ',
                           11: 'පාර්ශව',
                           12: 'හෝ',
                           13: 'පෙර',
                           14: 'වැ',
                           15: 'භූමි',
                           16: 'ස්පර්ශ',
                           17: 'කර',
                           18: 'පාදතල',
                           19: 'මධ්ය',
                           20: 'ජිද',
                           21: 'හෝ',
                           22: 'ව',
                           23: 'පත්ල',
                           24: 'නඟ',
                           25: 'කලද',
                           26: 'අග්රපාදතලාදීන්',
                           27: 'කෙරෙන්',
                           28: 'අන්යතර',
                           29: 'ස්ථානයෙක්',
                           30: 'පෙර',
                           31: 'වැ',
                           32: 'නඟ'},
                          28: {0: 'මොවුන්',
                           1: 'පතුල',
                           2: 'ව',
                           3: 'කල',

In [7]:
lemma_rows = []

for century, sentences in tqdm(century_embeddings.items(), desc="Processing Instances"):
    # Get the list of original text for this century
    # Replace 'all_original_texts' with your actual text variable
    raw_texts = century_tokens.get(century, []) 

    for s_idx, sentence_data in enumerate(sentences):
        # Capture the full sentence text for this index
        full_sentence_text = raw_texts[s_idx] if s_idx < len(raw_texts) else "Text not found"
        
        for w_idx, (word, vector) in enumerate(sentence_data):
            lemma = lemma_lookup[century].get(s_idx, {}).get(w_idx)
            
            if lemma:
                lemma_rows.append({
                    "century": int(century), # Convert to int for easier filtering
                    "word": word,
                    "lemma": lemma,
                    "vector": vector.numpy(),
                    "sentence_text": full_sentence_text  # <--- CRITICAL ADDITION
                })

df_results = pd.DataFrame(lemma_rows)

Processing Instances: 100%|██████████| 6/6 [00:00<00:00, 16.99it/s]

In [8]:
df_results = pd.DataFrame(lemma_rows)

In [9]:
df_results.head()

,century,word,lemma,vector,sentence_text
0,13,අප,අප,"[-0.017851107, -0.044579446, -0.040111683, 0.0...","[අප, බුදුන්, සාරාසකි, කප්සුවහස්, මතුයෙහි, කුලු..."
1,13,බුදුන්,බුදුන්,"[0.041268058, -0.035116285, -0.028367188, 0.00...","[අප, බුදුන්, සාරාසකි, කප්සුවහස්, මතුයෙහි, කුලු..."
2,13,සාරාසකි,සාරාස,"[-0.018791229, 0.004046296, -0.040097833, 0.03...","[අප, බුදුන්, සාරාසකි, කප්සුවහස්, මතුයෙහි, කුලු..."
3,13,කප්සුවහස්,කප්සුවහස,"[-0.014488558, 0.00863839, -0.033872638, 0.037...","[අප, බුදුන්, සාරාසකි, කප්සුවහස්, මතුයෙහි, කුලු..."
4,13,මතුයෙහි,මතු,"[0.030637398, -0.0062566586, -0.05201265, 0.04...","[අප, බුදුන්, සාරාසකි, කප්සුවහස්, මතුයෙහි, කුලු..."

In [10]:
def get_lemma_map(sub_df):
    l_map = {}
    for idx, row in sub_df.iterrows():
        l = row['lemma']
        
        # 1. THE FIX: Initialize the 'texts' list here
        if l not in l_map: 
            l_map[l] = {
                'vecs': [], 
                'indices': [], 
                'texts': []  # <--- MUST ADD THIS LINE
            }
        
        l_map[l]['vecs'].append(np.array(row['vector']))
        l_map[l]['indices'].append(idx)
        
        # 2. Now this line will work because the key exists
        sentence_string = " ".join(row['sentence_text']) if isinstance(row['sentence_text'], list) else row['sentence_text']
        l_map[l]['texts'].append(sentence_string)
        
    return l_map

In [11]:
# # 3. Define the LOO Logic
# def run_loo(l_old, l_new):
#     v_old = np.array(l_old['vecs'])
#     v_new = np.array(l_new['vecs'])
#     ids_new = l_new['indices']
#     texts_new = l_new['texts']
    
#     c_old = np.mean(v_old, axis=0)
#     c_new = np.mean(v_new, axis=0)
    
#     # Standard Drift (Distance between full averages)
#     base_dist = 1 - np.clip(cosine_similarity(c_old.reshape(1,-1), c_new.reshape(1,-1))[0][0], -1, 1)
    
#     loo_dists = []
#     impacts = []
    
#     for j in range(len(v_new)):
#         mask = np.ones(len(v_new), dtype=bool)
#         mask[j] = False
#         if np.any(mask):
#             c_loo = np.mean(v_new[mask], axis=0)
#             d_loo = 1 - np.clip(cosine_similarity(c_old.reshape(1,-1), c_loo.reshape(1,-1))[0][0], -1, 1)
#             loo_dists.append(d_loo)
#             impacts.append(base_dist - d_loo)
#         else:
#             loo_dists.append(base_dist)
#             impacts.append(0)

#     best_index = np.argmax(impacts)
    
#     return {
#         'persistent_shift': min(loo_dists),
#         'global_distance': base_dist,
#         'innovation_instances': texts_new[best_index], # Now texts_new is defined!
#         'max_impact': max(impacts) if impacts else 0
#     }

In [12]:
def run_multi_loo(l_old, l_new):
    v_old = np.array(l_old['vecs'])
    v_new = np.array(l_new['vecs'])
    texts_new = l_new['texts']
    
    c_old = np.mean(v_old, axis=0).reshape(1, -1)
    
    # 1. Global Distance (The baseline)
    c_new_full = np.mean(v_new, axis=0).reshape(1, -1)
    global_distance = 1 - np.clip(cosine_similarity(c_old, c_new_full)[0][0], -1, 1)
    
    sentence_impacts = []
    
    # 2. Leave-One-Out (One by one)
    for j in range(len(v_new)):
        mask = np.ones(len(v_new), dtype=bool)
        mask[j] = False
        
        if np.any(mask):
            c_loo = np.mean(v_new[mask], axis=0).reshape(1, -1)
            dist_without_j = 1 - np.clip(cosine_similarity(c_old, c_loo)[0][0], -1, 1)
            # Impact is the reduction in distance
            impact = global_distance - dist_without_j
            sentence_impacts.append({'text': texts_new[j], 'impact': impact, 'index': j})
        else:
            sentence_impacts.append({'text': texts_new[j], 'impact': 0, 'index': j})

    # 3. Dynamic Filtering (The "Gap" Logic)
    # Sort by impact descending
    sorted_impacts = sorted(sentence_impacts, key=lambda x: x['impact'], reverse=True)
    
    # Filter for sentences that actually pull away (impact > 0)
    positive_impacts = [s for s in sorted_impacts if s['impact'] > 0]
    
    informers = []
    if positive_impacts:
        # We take the top influencer, then any others that are close to it
        # (within 50% of the top impact) to capture clusters/multiple senses
        max_imp = positive_impacts[0]['impact']
        informers = [s for s in positive_impacts if s['impact'] >= (max_imp * 0.5)]

    # 4. Group Impact (Persistent Shift Calculation)
    innovator_indices = [s['index'] for s in informers]
    mask_stable = np.ones(len(v_new), dtype=bool)
    
    if innovator_indices:
        mask_stable[innovator_indices] = False
    
    if np.any(mask_stable):
        c_stable = np.mean(v_new[mask_stable], axis=0).reshape(1, -1)
        persistent_shift = 1 - np.clip(cosine_similarity(c_old, c_stable)[0][0], -1, 1)
    else:
        # If all sentences were informers (Rare), shift is global
        persistent_shift = global_distance

    return {
        'global_distance': global_distance,
        'persistent_shift': persistent_shift,
        'informer_data': [(s['text'], s['impact']) for s in informers],
        'innovation_count': len(informers),
        'max_impact': max_imp if positive_impacts else 0
    }

In [13]:
def analyze_semantic_drift(df, target_lemma=None, old_century=14, new_century=20):
    # Standardize Century Column
    df['century_str'] = df['century'].astype(str)
    
    # 1. Filter and Map
    map_old = get_lemma_map(df[df['century_str'] == str(old_century)])
    map_new = get_lemma_map(df[df['century_str'] == str(new_century)])

    # 2. Execution Logic
    if target_lemma:
        if target_lemma in map_old and target_lemma in map_new:
            return run_multi_loo(map_old[target_lemma], map_new[target_lemma])
        return "Lemma not found in both centuries."
    else:
        all_results = []
        common = set(map_old.keys()) & set(map_new.keys())
        for l in common:
            # Check length of the vecs list to ensure LOO is possible
            if len(map_new[l]['vecs']) >= 2: 
                res = run_multi_loo(map_old[l], map_new[l])
                res['lemma'] = l
                all_results.append(res)
        
        return pd.DataFrame(all_results).sort_values('persistent_shift', ascending=False)

In [14]:
# results_df = analyze_semantic_drift(df_results, old_century=13, new_century=20)

In [15]:
# results_df.head(30)

In [16]:
# word_stats = analyze_semantic_drift(df_results, target_lemma='සතර', old_century=19, new_century=15)
# print(word_stats)

In [17]:
# word_stats

In [19]:
with open("../Data/consistent_keys_lemmas.json", "r", encoding="utf-8") as f:
    consistent_keys = json.load(f)

In [20]:
# # 1. Initialize an empty list to store the results
# all_lemma_stats = []

# # 2. Iterate through your target lemmas
# all_lemma_stats = []

# for lemma in consistent_keys:
#     word_stats = analyze_semantic_drift(df_results, target_lemma=lemma, old_century=15, new_century=19)
    
#     # Check if word_stats is actually a dictionary before assigning
#     if isinstance(word_stats, dict):
#         word_stats['lemma'] = lemma
#         all_lemma_stats.append(word_stats)
#     else:
#         print(f"Skipping lemma '{lemma}': Function returned {type(word_stats)} instead of dict.")

# analysis_df = pd.DataFrame(all_lemma_stats)

# # 4. Optional: Calculate the Impact Ratio for your thesis
# # This shows what % of the drift is explained by the innovations found
# analysis_df['drift_reduction_pct'] = (
#     (analysis_df['global_distance'] - analysis_df['persistent_shift']) / 
#     analysis_df['global_distance'] * 100
# ).fillna(0)

# # Reorder columns for better readability
# cols = ['lemma', 'global_distance', 'persistent_shift', 'drift_reduction_pct', 'innovation_count', 'informer_data']
# analysis_df = analysis_df[cols]

# # Display top drifted words
# print(analysis_df.sort_values(by='global_distance', ascending=False).head(10))

In [21]:
# 1. Configuration
centuries = [13, 14, 15, 18, 19, 20]
century_pairs = list(permutations(centuries, 2))
all_lag_stats = []

print(f"Processing {len(century_pairs)} permutations for {len(consistent_keys)} lemmas...")

# 2. Outer loop for Century Pairs
for old_c, new_c in tqdm(century_pairs, desc="Century Permutations"):
    
    perm_label = f"{old_c}_{new_c}"
    
    # Inner loop for Lemmas
    for lemma in consistent_keys:
        # We need the count of the target century instances
        # Assuming df_results is your source DataFrame
        target_instances = df_results[(df_results['lemma'] == lemma) & (df_results['century'] == new_c)]
        total_count = len(target_instances)
        
        # Call analysis
        word_stats = analyze_semantic_drift(
            df_results, 
            target_lemma=lemma, 
            old_century=old_c, 
            new_century=new_c
        )
        
        if isinstance(word_stats, dict):
            word_stats['lemma'] = lemma
            word_stats['permutation'] = perm_label
            word_stats['anchor_century'] = old_c
            word_stats['target_century'] = new_c
            word_stats['total_instance_count'] = total_count # New column added
            word_stats['direction'] = "Forward" if new_c > old_c else "Reverse"
            
            all_lag_stats.append(word_stats)

# 3. Create DataFrame
analysis_df = pd.DataFrame(all_lag_stats)

# 4. Final Processing
if not analysis_df.empty:
    # Handle percentages
    analysis_df['drift_reduction_pct'] = 0.0
    mask = (analysis_df['global_distance'] > 0)
    analysis_df.loc[mask, 'drift_reduction_pct'] = (
        (analysis_df['global_distance'] - analysis_df['persistent_shift']) / 
        analysis_df['global_distance'] * 100
    )

    # 5. Column Organization
    cols = [
        'lemma', 'permutation', 'anchor_century', 'target_century', 
        'direction', 'global_distance', 'persistent_shift', 
        'drift_reduction_pct', 'innovation_count', 'total_instance_count', 'informer_data'
    ]
    analysis_df = analysis_df[[c for c in cols if c in analysis_df.columns]]

    print(f"\nSuccess: {len(analysis_df)} rows generated.")

Processing 30 permutations for 261 lemmas...

Century Permutations: 100%|██████████| 30/30 [43:44<00:00, 87.48s/it]

Success: 7830 rows generated.

In [22]:
analysis_df.sort_values(by='drift_reduction_pct', ascending=False)

          lemma permutation  anchor_century  target_century direction  \
4536      කෙසේද       18_15              18              15   Reverse
1498          ම       14_13              14              13   Reverse
4337       ලද්ද       18_14              18              14   Reverse
6647        ආදි       20_13              20              13   Reverse
4484        යත්       18_15              18              15   Reverse
5342        ආදි       19_13              19              13   Reverse
977         පාද       13_19              13              19   Forward
3629     ප්රකාර       15_19              15              19   Forward
5438        රාජ       19_13              19              13   Reverse
5146          ය       18_20              18              20   Forward
4133        රාජ       18_13              18              13   Reverse
2755          ව       15_13              15              13   Reverse
4624          ය       18_15              18              15   Reverse
7098         කර       20_15              20              15   Reverse
5275         රජ       19_13              19              13   Reverse
2744     හෙයින්       15_13              15              13   Reverse
648           ද       13_18              13              18   Forward
1189          ව       13_20              13              20   Forward
920          නම       13_19              13              19   Forward
3531     කෙරෙන්       15_19              15              19   Forward
2233          ව       14_19              14              19   Forward
5365          ව       19_13              19              13   Reverse
7728         හා       20_19              20              19   Reverse
7171         සේ       20_15              20              15   Reverse
6324          ඊ       19_20              19              20   Forward
6512          එ       19_20              19              20   Forward
2324     ප්රකාර       14_19              14              19   Forward
3630         සත       15_19              15              19   Forward
7237        ඥාන       20_15              20              15   Reverse
2732        ආදි       15_13              15              13   Reverse
4340        නාම       18_14              18              14   Reverse
942          හා       13_19              13              19   Forward
7206         හා       20_15              20              15   Reverse
5468          එ       19_13              19              13   Reverse
2623       සත්ව       15_13              15              13   Reverse
6659     හෙයින්       20_13              20              13   Reverse
4108          ම       18_13              18              13   Reverse
6670          ව       20_13              20              13   Reverse
5276      කිරීම       19_13              19              13   Reverse
4102          ය       18_13              18              13   Reverse
6404     වහන්සේ       19_20              19              20   Forward
1385        පමණ       14_13              14              13   Reverse
1610        භාව       14_15              14              15   Forward
5104          ව       18_20              18              20   Forward
1523        රාජ       14_13              14              13   Reverse
420          හා       13_15              13              15   Forward
3799          ව       15_20              15              20   Forward
6819      සර්වඥ       20_14              20              14   Reverse
2632          ඉ       15_13              15              13   Reverse
7805     ප්රකාර       20_19              20              19   Reverse
3538          ව       15_19              15              19   Forward
2831         ලබ       15_13              15              13   Reverse
2661         කර       15_13              15              13   Reverse
4843          ව       18_19              18              19   Forward
5413          ම       19_13              19              13   Reverse
6743        රාජ       20_13              20              13   Reverse
6712          ය       20_13              20              13   Reverse
928           ව       13_19              13              19   Forward
2494          ව       14_20              14              20   Forward
7342      යුක්ත       20_18              20              18   Reverse
6682     බුදුන්       20_13              20              13   Reverse
2289      කරන්න       14_19              14              19   Forward
7707     කෙරෙන්       20_19              20              19   Reverse
4836     කෙරෙන්       18_19              18              19   Forward
6449        ගොස       19_20              19              20   Forward
5019          ඊ       18_20              18              20   Forward
4934     ප්රකාර       18_19              18              19   Forward
2797          ය       15_13              15              13   Reverse
5407          ය       19_13              19              13   Reverse
4885          ය       18_19              18              19   Forward
5960        රාජ       19_15              19              15   Reverse
1656        පුර       14_15              14              15   Forward
5666        ගොස       19_14              19              14   Reverse
405          මහ       13_15              13              15   Forward
3962        යත්       18_13              18              13   Reverse
3254        ආදි       15_18              15              18   Forward
3868         වි       15_20              15              20   Forward
498          සත       13_15              13              15   Forward
4961          ණ       18_20              18              20   Forward
796        සත්ව       13_19              13              19   Forward
7021     විසින්       20_14              20              14   Reverse
5120       ලද්ද       18_20              18              20   Forward
510         ඇති       13_15              13              15   Forward
6457          ම       19_20              19              20   Forward
6587       කිරි       20_13              20              13   Reverse
7265        රාජ       20_15              20              15   Reverse
1016        යම්       13_19              13              19   Forward
135          වඩ       13_14              13              14   Forward
7817          එ       20_19              20              19   Reverse
1427        ආදි       14_13              14              13   Reverse
5866         සේ       19_15              19              15   Reverse
6129          ද       19_18              19              18   Reverse
918          වඩ       13_19              13              19   Forward
5377     බුදුන්       19_13              19              13   Reverse
6487         මී       19_20              19              20   Forward
1594        නවත       14_15              14              15   Forward
2855        කොට       15_13              15              13   Reverse
4686        ඇති       18_15              18              15   Reverse
4821        රැස       18_19              18              19   Forward
7445         නම       20_18              20              18   Reverse
5726        කොට       19_14              19              14   Reverse
3006         වඩ       15_14              15              14   Reverse
6718          ම       20_13              20              13   Reverse
6125        ආදි       19_18              19              18   Reverse
2123         හර       14_19              14              19   Forward
7163         වස       20_15              20              15   Reverse
7520       ශරීර       20_18              20              18   Reverse
7406      තන්හි       20_18              20              18   Reverse
6264         තම       19_20              19              20   Forward
3269         නම       15_18              15              18   Forward
6286          ඉ       19_20              19              20   Forward
5621     වහන්සේ       19_14              19              14   Reverse
2735       යෙහි       15_13              15              13   Reverse
6654          ඒ       20_13              20              13   Reverse
3667       සත්ව       15_20              15              20   Forward
2984       ධර්ම       15_14              15              14   Reverse
1815        ඇති       14_15              14              15   Forward
7623      දෙදෙන       20_19              20              19   Reverse
1492          ය       14_13              14              13   Reverse
535        සත්ව       13_18              13              18   Forward
7521    සංඛ්යාත       20_18              20              18   Reverse
1348        ආදී       14_13              14              13   Reverse
2313         ලො       14_19              14              19   Forward
1450          ව       14_13              14              13   Reverse
2333        කොට       14_19              14              19   Forward
245         කොට       13_14              13              14   Forward
1019     ප්රකාර       13_19              13              19   Forward
1242        කිය       13_20              13              20   Forward
360       කෙසේද       13_15              13              15   Forward
274        සත්ව       13_15              13              15   Forward
4715       දෙවි       18_19              18              19   Forward
4494         වඳ       18_15              18              15   Reverse
1439     හෙයින්       14_13              14              13   Reverse
6746         ලබ       20_13              20              13   Reverse
4655        රාජ       18_15              18              15   Reverse
888        මෙහි       13_19              13              19   Forward
4628     බැවින්       18_15              18              15   Reverse
5368        යයි       19_13              19              13   Reverse
7582       සත්ව       20_19              20              19   Reverse
2223         වඩ       14_19              14              19   Forward
3409         නග       15_19              15              19   Forward
2947      එයින්       15_14              15              14   Reverse
409         යයි       13_15              13              15   Forward
3258          ද       15_18              15              18   Forward
2349         තම       14_20              14              20   Forward
6547          ඉ       20_13              20              13   Reverse
2040    සංඛ්යාත       14_18              14              18   Forward
5793         කර       19_15              19              15   Reverse
5418        කිය       19_13              19              13   Reverse
1008         ලො       13_19              13              19   Forward
2560      සියලු       14_20              14              20   Forward
6723        කිය       20_13              20              13   Reverse
7823        තවද       20_19              20              19   Reverse
620       තන්හි       13_18              13              18   Forward
5465        කොට       19_13              19              13   Reverse
2803          ම       15_13              15              13   Reverse
2304       නුවර       14_19              14              19   Forward
2663         දන       15_13              15              13   Reverse
6759       අර්ථ       20_13              20              13   Reverse
5716     විසින්       19_14              19              14   Reverse
2269       තිබෙ       14_19              14              19   Forward
4347        කරණ       18_14              18              14   Reverse
1566         තම       14_15              14              15   Forward
5282       කිරි       19_13              19              13   Reverse
4889     බැවින්       18_19              18              19   Forward
459         කිය       13_15              13              15   Forward
334          එම       13_15              13              15   Forward
4465        නවත       18_15              18              15   Reverse
5144        ගොස       18_20              18              20   Forward
1079         හර       13_20              13              20   Forward
351         පුර       13_15              13              15   Forward
1028        කොට       13_19              13              19   Forward
7665        රූප       20_19              20              19   Reverse
2173         හට       14_19              14              19   Forward
6309        සැප       19_20              19              20   Forward
7272         ලො       20_15              20              15   Reverse
7767        කිය       20_19              20              19   Reverse
473        ශරීර       13_15              13              15   Forward
7768         දෙ       20_19              20              19   Reverse
1517       ශරීර       14_13              14              13   Reverse
4363          ය       18_14              18              14   Reverse
1277        යම්       13_20              13              20   Forward
5771       මෙන්       19_15              19              15   Reverse
1166        ආදි       13_20              13              20   Forward
3011     වහන්සේ       15_14              15              14   Reverse
3098        සකල       15_14              15              14   Reverse
2849        සිත       15_13              15              13   Reverse
6957        කරණ       20_14              20              14   Reverse
7157         පද       20_15              20              15   Reverse
1759          ම       14_15              14              15   Forward
4349         බල       18_14              18              14   Reverse
33        සර්වඥ       13_14              13              14   Forward
227         සකල       13_14              13              14   Forward
1255      සියලු       13_20              13              20   Forward
5229      කල්හි       19_13              19              13   Reverse
3866       ශරීර       15_20              15              20   Forward
2384         හර       14_20              14              20   Forward
6783         පස       20_13              20              13   Reverse
7523         බව       20_18              20              18   Reverse
3604      සියලු       15_19              15              19   Forward
3839        ගොස       15_20              15              20   Forward
235      විසින්       13_14              13              14   Forward
6399         වඩ       19_20              19              20   Forward
4853       ධාතු       18_19              18              19   Forward
6334     නොයෙක්       19_20              19              20   Forward
5138         ගත       18_20              18              20   Forward
3100        උපද       15_14              15              14   Reverse
239         සිත       13_14              13              14   Forward
406           ව       13_15              13              15   Forward
4042       සිටි       18_13              18              13   Reverse
1690         සේ       14_15              14              15   Forward
7829         බස       20_19              20              19   Reverse
834          කර       13_19              13              19   Forward
5273         දන       19_13              19              13   Reverse
1456        දහස       14_13              14              13   Reverse
6031        නවත       19_18              19              18   Reverse
6398     හෙයින්       19_20              19              20   Forward
898          කළ       13_19              13              19   Forward
1181         නම       13_20              13              20   Forward
1326       යහපත       14_13              14              13   Reverse
7076       මෙන්       20_15              20              15   Reverse
842        සඳහා       13_19              13              19   Forward
7210         මෙ       20_15              20              15   Reverse
2681          ස       15_13              15              13   Reverse
6360        රූප       19_20              19              20   Forward
1806      යනාදී       14_15              14              15   Forward
140      වහන්සේ       13_14              13              14   Forward
2000         බල       14_18              14              18   Forward
5982      යනාදී       19_15              19              15   Reverse
4899      කරන්න       18_19              18              19   Forward
4892        පාද       18_19              18              19   Forward
1140        රූප       13_20              13              20   Forward
7814        කොට       20_19              20              19   Reverse
5720        සිත       19_14              19              14   Reverse
4832     හෙයින්       18_19              18              19   Forward
7434          ද       20_18              20              18   Reverse
5654         බල       19_14              19              14   Reverse
6650       යෙහි       20_13              20              13   Reverse
7698          ඒ       20_19              20              19   Reverse
415        වැසි       13_15              13              15   Forward
5210      දක්වා       18_20              18              20   Forward
7763        පාද       20_19              20              19   Reverse
1022        සිත       13_19              13              19   Forward
3594      කරන්න       15_19              15              19   Forward
1613        යත්       14_15              14              15   Forward
2563         වි       14_20              14              20   Forward
5186        සකල       18_20              18              20   Forward
126           ද       13_14              13              14   Forward
5896       වැසි       19_15              19              15   Reverse
2677        ගුණ       15_13              15              13   Reverse
1305         තම       14_13              14              13   Reverse
7167     ප්රධාන       20_15              20              15   Reverse
6774        ඇති       20_13              20              13   Reverse
3865      සියලු       15_20              15              20   Forward
5557      එයින්       19_14              19              14   Reverse
1104          ඊ       13_20              13              20   Forward
2690        පමණ       15_13              15              13   Reverse
5514      සර්වඥ       19_14              19              14   Reverse
3007         අස       15_14              15              14   Reverse
3639        ගන්       15_19              15              19   Forward
1526         ලබ       14_13              14              13   Reverse
4076       ලද්ද       18_13              18              13   Reverse
5390         එක       19_13              19              13   Reverse
7649        පමණ       20_19              20              19   Reverse
6265        දකි       19_20              19              20   Forward
2530       තිබෙ       14_20              14              20   Forward
1068         කල       13_20              13              20   Forward
7176          ඒ       20_15              20              15   Reverse
5271         කර       19_13              19              13   Reverse
6463         දෙ       19_20              19              20   Forward
6315         කර       19_20              19              20   Forward
3217         හට       15_18              15              18   Forward
4824          ද       18_19              18              19   Forward
2362       සත්ව       14_20              14              20   Forward
5478         පස       19_13              19              13   Reverse
1440         වඩ       14_13              14              13   Reverse
3506       ධර්ම       15_19              15              19   Forward
1529        දවස       14_13              14              13   Reverse
7336        නවත       20_18              20              18   Reverse
2261         බල       14_19              14              19   Forward
4316     වහන්සේ       18_14              18              14   Reverse
6675        දෙන       20_13              20              13   Reverse
4817          ක       18_19              18              19   Forward
6673        යයි       20_13              20              13   Reverse

In [23]:
# analysis_df = analysis_df.sort_values(by='drift_reduction_pct', ascending=False)

In [24]:
analysis_df.to_csv("../Data/XLM-R_lemma_drift_analysis.csv", index=False, encoding='utf-8-sig')